version: "3"
services:
  oppia:
    build:
      context: ../.
      dockerfile: ./docker/Dockerfile_frontend-tests
    ports:
      - "8181:8181"
      - "8000:8000"
      - "9876:9876"
    volumes:
      - ..:/home/oppia/:rw
    entrypoint: ["/home/oppia/scripts/run_frontend_tests.sh"]
